In [74]:
import numpy as np
import pandas as pd

In [75]:
pd.__version__

'3.0.3'

In [76]:
! wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2026-07-10 10:39:28--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response...

200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv.2’

car_fuel_efficiency 100%[===================>] 853.70K  74.6KB/s    in 14s

2026-07-10 10:39:43 (62.2 KB/s) - ‘car_fuel_efficiency.csv.2’ saved [874188/874188]

In [77]:
df = pd.read_csv('car_fuel_efficiency.csv')

df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [78]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   engine_displacement  9704 non-null   int64
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64
 6   origin               9704 non-null   str
 7   fuel_type            9704 non-null   str
 8   drivetrain           9704 non-null   str
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), str(3)
memory usage: 834.1 KB

In [79]:
df['fuel_type'].nunique()

2

In [80]:
(df.isna().sum() > 0).sum()

np.int64(4)

In [81]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [82]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [71]:
df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [83]:
df.horsepower.describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [84]:
df['horsepower'] = df['horsepower'].fillna(df.horsepower.mean())
df.horsepower.describe()

count    9704.000000
mean      149.657292
std        28.768797
min        37.000000
25%       131.000000
50%       149.657292
75%       168.000000
max       271.000000
Name: horsepower, dtype: float64

In [94]:
X = df.loc[df['origin'] == 'Asia', ['vehicle_weight', 'model_year']].head(7)
X

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [95]:
XTX = X.T.dot(X)
XTX

                vehicle_weight    model_year
vehicle_weight    6.224833e+07  4.143122e+07
model_year        4.143122e+07  2.837334e+07

In [96]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]


w = np.linalg.solve(XTX, X.T.dot(y))
w

array([0.01386421, 0.5049067 ])