In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns

%matplotlib inline

In [32]:
df = pd.read_csv("churn.csv")

In [33]:
df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [34]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

df.head().T

,0,1,2,3,4
customerid,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
seniorcitizen,0,0,0,0,0
partner,Yes,No,No,No,No
dependents,No,No,No,No,No
tenure,1,34,2,45,2
phoneservice,No,Yes,Yes,No,Yes
multiplelines,No phone service,No,No,No phone service,No
internetservice,DSL,DSL,DSL,DSL,Fiber optic
onlinesecurity,No,Yes,Yes,Yes,No
onlinebackup,Yes,No,Yes,No,No
deviceprotection,No,Yes,No,Yes,No
techsupport,No,No,No,Yes,No
streamingtv,No,No,No,No,No
streamingmovies,No,No,No,No,No
contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
paperlessbilling,Yes,No,Yes,No,Yes
paymentmethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,No,No,Yes,No,Yes

In [35]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [36]:
categorical_columns = [
    column for column in df.columns if df[column].dtype == "str"
]

for col in categorical_columns:
    df[col] = df[col].str.lower().str.replace(" ", "_")
    
df.head().T

,0,1,2,3,4
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu
gender,female,male,male,male,female
seniorcitizen,0,0,0,0,0
partner,yes,no,no,no,no
dependents,no,no,no,no,no
tenure,1,34,2,45,2
phoneservice,no,yes,yes,no,yes
multiplelines,no_phone_service,no,no,no_phone_service,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic
onlinesecurity,no,yes,yes,yes,no
onlinebackup,yes,no,yes,no,no
deviceprotection,no,yes,no,yes,no
techsupport,no,no,no,yes,no
streamingtv,no,no,no,no,no
streamingmovies,no,no,no,no,no
contract,month-to-month,one_year,month-to-month,one_year,month-to-month
paperlessbilling,yes,no,yes,no,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,no,no,yes,no,yes

In [37]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [38]:
tc = pd.to_numeric(df['totalcharges'], errors="coerce")

In [39]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors="coerce")

In [40]:
df.totalcharges = df.totalcharges.fillna(0)

In [41]:
df[tc.isnull()][['customerid', 'totalcharges']]

      customerid  totalcharges
488   4472-lvygi           0.0
753   3115-czmzd           0.0
936   5709-lvoeq           0.0
1082  4367-nuyao           0.0
1340  1371-dwpaz           0.0
3331  7644-omvmy           0.0
3826  3213-vvolg           0.0
4380  2520-sgtta           0.0
5218  2923-arzlg           0.0
6670  4075-wkniu           0.0
6754  2775-sefee           0.0

In [42]:
df.churn = (df.churn == 'yes').astype(int)

In [43]:
df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,yes,electronic_check,29.85,29.85,0
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,one_year,no,mailed_check,56.95,1889.50,0
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailed_check,53.85,108.15,1
3,7795-cfocw,male,0,no,no,45,no,no_phone_service,dsl,yes,...,yes,yes,no,no,one_year,no,bank_transfer_(automatic),42.30,1840.75,0
4,9237-hqitu,female,0,no,no,2,yes,no,fiber_optic,no,...,no,no,no,no,month-to-month,yes,electronic_check,70.70,151.65,1

### Spliting Datasets

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)

In [46]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [47]:
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [48]:
df_full_train = df_full_train.reset_index(drop=True)

df_train: pd.DataFrame = df_train.reset_index(drop=True)
df_val: pd.DataFrame = df_val.reset_index(drop=True)
df_test: pd.DataFrame = df_test.reset_index(drop=True)

In [49]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [50]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

### EDA (Explotary Data Analysis)

In [51]:
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [52]:
df_full_train.churn.value_counts(normalize=True)

churn
0    0.734469
1    0.265531
Name: proportion, dtype: float64

In [53]:
global_churn_rate = df_full_train.churn.mean()
round(global_churn_rate, 2)

np.float64(0.27)

In [54]:
df_full_train.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [55]:
numerical = [
       'tenure', 
       'monthlycharges', 
       'totalcharges'
]

categorical = [
       'gender', 
       'seniorcitizen', 
       'partner', 
       'dependents', 
       'phoneservice', 
       'multiplelines', 
       'internetservice',
       'onlinesecurity', 
       'onlinebackup', 
       'deviceprotection', 
       'techsupport',
       'streamingtv', 
       'streamingmovies', 
       'contract', 
       'paperlessbilling',
       'paymentmethod'
]

In [56]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

### Feature Importance

In [58]:
df_group = df_full_train.groupby("gender").churn.agg(['mean', 'count'])

df_group['risk'] = df_group['mean'] / global_churn_rate
df_group['difference'] = df_group['mean'] - global_churn_rate

df_group

            mean  count      risk  difference
gender
female  0.270841   2747  1.019998    0.005310
male    0.260478   2887  0.980971   -0.005053

In [ ]:
from IPython.display import display

In [62]:
for column in categorical:

    df_group = df_full_train.groupby(column).churn.agg(['mean', 'count'])

    df_group['risk'] = df_group['mean'] / global_churn_rate
    df_group['difference'] = df_group['mean'] - global_churn_rate

    display(df_group)
    print()

            mean  count      risk  difference
gender
female  0.270841   2747  1.019998    0.005310
male    0.260478   2887  0.980971   -0.005053

                   mean  count      risk  difference
seniorcitizen
0              0.237098   4728  0.892922   -0.028433
1              0.413907    906  1.558793    0.148377

             mean  count      risk  difference
partner
no       0.326446   2904  1.229411    0.060916
yes      0.200733   2730  0.755968   -0.064798

                mean  count      risk  difference
dependents
no          0.312326   3951  1.176233    0.046795
yes         0.155674   1683  0.586276   -0.109856

                  mean  count      risk  difference
phoneservice
no            0.253623    552  0.955156   -0.011908
yes           0.266824   5082  1.004871    0.001293

                      mean  count      risk  difference
multiplelines
no                0.251397   2685  0.946771   -0.014134
no_phone_service  0.253623    552  0.955156   -0.011908
yes               0.284105   2397  1.069952    0.018574

                     mean  count      risk  difference
internetservice
dsl              0.191851   1939  0.722521   -0.073679
fiber_optic      0.415558   2481  1.565010    0.150028
no               0.076606   1214  0.288502   -0.188924

                         mean  count      risk  difference
onlinesecurity
no                   0.416014   2810  1.566727    0.150484
no_internet_service  0.076606   1214  0.288502   -0.188924
yes                  0.145342   1610  0.547363   -0.120189

                         mean  count      risk  difference
onlinebackup
no                   0.398693   2448  1.501494    0.133162
no_internet_service  0.076606   1214  0.288502   -0.188924
yes                  0.216531   1972  0.815467   -0.048999

                         mean  count      risk  difference
deviceprotection
no                   0.387706   2489  1.460117    0.122175
no_internet_service  0.076606   1214  0.288502   -0.188924
yes                  0.226825   1931  0.854234   -0.038705

                         mean  count      risk  difference
techsupport
no                   0.413472   2791  1.557153    0.147941
no_internet_service  0.076606   1214  0.288502   -0.188924
yes                  0.152855   1629  0.575657   -0.112676

                         mean  count      risk  difference
streamingtv
no                   0.335418   2239  1.263197    0.069887
no_internet_service  0.076606   1214  0.288502   -0.188924
yes                  0.298945   2181  1.125841    0.033415

                         mean  count      risk  difference
streamingmovies
no                   0.333333   2223  1.255348    0.067803
no_internet_service  0.076606   1214  0.288502   -0.188924
yes                  0.301320   2197  1.134784    0.035789

                    mean  count      risk  difference
contract
month-to-month  0.426533   3083  1.606340    0.161002
one_year        0.117987   1212  0.444343   -0.147544
two_year        0.028379   1339  0.106878   -0.237151

                     mean  count      risk  difference
paperlessbilling
no                0.16414   2309  0.618159   -0.101390
yes               0.33594   3325  1.265164    0.070409

                               mean  count      risk  difference
paymentmethod
bank_transfer_(automatic)  0.174475   1238  0.657080   -0.091056
credit_card_(automatic)    0.152404   1227  0.573961   -0.113126
electronic_check           0.449921   1887  1.694420    0.184390
mailed_check               0.190328   1282  0.716782   -0.075203

### Feature Importance: Mutal Information

In [63]:
from sklearn.metrics import mutual_info_score

In [68]:
for column in categorical:
    
    print("column:", column)
    mutual_in_score = mutual_info_score(df_full_train.churn, df_full_train[column])
    print(round(mutual_in_score, 2))

column: gender
0.0
column: seniorcitizen
0.01
column: partner
0.01
column: dependents
0.01
column: phoneservice
0.0
column: multiplelines
0.0
column: internetservice
0.05
column: onlinesecurity
0.06
column: onlinebackup
0.05
column: deviceprotection
0.04
column: techsupport
0.06
column: streamingtv
0.03
column: streamingmovies
0.03
column: contract
0.1
column: paperlessbilling
0.02
column: paymentmethod
0.04