In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns

%matplotlib inline

In [42]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv -O data.csv

--2026-07-15 11:19:13--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443...

connected.
HTTP request sent, awaiting response... 200 OK
Length: 80876 (79K) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]  78.98K  --.-KB/s    in 0.1s

2026-07-15 11:19:14 (554 KB/s) - ‘data.csv’ saved [80876/80876]

In [43]:
df = pd.read_csv('data.csv')

In [44]:
df.head()

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1

In [45]:
df.isnull().sum()

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [46]:
df.dtypes

lead_source                     str
industry                        str
number_of_courses_viewed      int64
annual_income               float64
employment_status               str
location                        str
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [47]:
categorical = ['lead_source', 'industry', 'employment_status', 'location']
numerical = ['number_of_courses_viewed', 'annual_income', 'interaction_count', 'lead_score']

In [48]:
for col in categorical:
    df[col] = df[col].fillna('NA')


for col in numerical:
    df[col] = df[col].fillna(0.0)

In [49]:
df.isnull().sum()

lead_source                 0
industry                    0
number_of_courses_viewed    0
annual_income               0
employment_status           0
location                    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [50]:
df.industry.head()

0            NA
1        retail
2    healthcare
3        retail
4     education
Name: industry, dtype: str

In [51]:
df[['lead_source', 'industry']].groupby('industry').agg(['count'])

              lead_source
                    count
industry
NA                    134
education             187
finance               200
healthcare            187
manufacturing         174
other                 198
retail                203
technology            179

In [52]:
df[numerical].corr()

,number_of_courses_viewed,annual_income,interaction_count,lead_score
number_of_courses_viewed,1.000000,0.009770,-0.023565,-0.004879
annual_income,0.009770,1.000000,0.027036,0.015610
interaction_count,-0.023565,0.027036,1.000000,0.009888
lead_score,-0.004879,0.015610,0.009888,1.000000

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [55]:
len(df_train), len(df_val), len(df_test)

(876, 293, 293)

In [56]:
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

del df_train['converted']
del df_val['converted']
del df_test['converted']

In [57]:
from sklearn.metrics import mutual_info_score

In [58]:
for col in categorical:
    mi = mutual_info_score(df_train[col].values, y_train)
    print(f'{col}: {mi:.4f}')

lead_source: 0.0354
industry: 0.0116
employment_status: 0.0129
location: 0.0045

In [59]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction import DictVectorizer

In [60]:
dv = DictVectorizer(sparse=False)

In [61]:

train_dicts = df_train[numerical + categorical].to_dict(orient='records')
X_train = dv.fit_transform(train_dicts)

val_dicts = df_val[numerical + categorical].to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [62]:
model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)

In [63]:
model.fit(X_train, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [64]:
y_pred = model.predict_proba(X_val)[:, 1] # not converted and converted probabilities

In [65]:
converted_decision = (y_pred >= 0.5)
(y_val == converted_decision).mean()

np.float64(0.6996587030716723)

In [66]:
model.score(X_val, y_val)

0.6996587030716723

In [67]:
dict_full_train = df_full_train[numerical + categorical].to_dict(orient='records')

X_full_train = dv.transform(dict_full_train)
y_full_train = df_full_train.converted.values

dict_test = df_test[numerical + categorical].to_dict(orient='records')
X_test = dv.transform(dict_test)

In [68]:
model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)
model.fit(X_full_train, y_full_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [69]:
model.score(X_test, y_test)

0.7372013651877133

### Feature Importance

In [70]:
global_converted = df['converted'].mean()

for col in categorical:
    
    df_group = df_full_train.groupby(col).converted.agg(['mean', 'count'])
    df_group['difference'] = df_group['mean'] - global_converted
    df_group['risk'] = df_group['mean'] / global_converted
    df_group.sort_values('difference', ascending=False, inplace=True)
    display(df_group)
    print()

                    mean  count  difference      risk
lead_source
referral        0.786408    206    0.167393  1.270418
NA              0.669725    109    0.050710  1.081920
organic_search  0.615721    229   -0.003295  0.994678
events          0.592965    199   -0.026050  0.957917
social_media    0.583333    216   -0.035682  0.942357
paid_ads        0.428571    210   -0.190444  0.692344

                   mean  count  difference      risk
industry
education      0.790210    143    0.171195  1.276560
manufacturing  0.621429    140    0.002414  1.003899
other          0.612903    155   -0.006112  0.990127
healthcare     0.593333    150   -0.025682  0.958512
retail         0.566265    166   -0.052750  0.914784
technology     0.562963    135   -0.056052  0.909450
NA             0.557522    113   -0.061493  0.900660
finance        0.556886    167   -0.062129  0.899633

                       mean  count  difference      risk
employment_status
employed           0.671937    253    0.052922  1.085493
student            0.659722    288    0.040707  1.065761
self_employed      0.635739    291    0.016724  1.027017
NA                 0.571429     84   -0.047586  0.923125
unemployed         0.462451    253   -0.156564  0.747075

                   mean  count  difference      risk
location
NA             0.680000     50    0.060985  1.098519
middle_east    0.644172    163    0.025157  1.040640
europe         0.641176    170    0.022161  1.035801
australia      0.612903    155   -0.006112  0.990127
africa         0.592857    140   -0.026158  0.957743
north_america  0.589888    178   -0.029127  0.952946
asia           0.588608    158   -0.030407  0.950878
south_america  0.554839    155   -0.064176  0.896325